#!/usr/bin/env bash
rm ./medusa/data/example_data/recons/?_face*.h5
for device in cpu gpu; do
    python ./set_package_version.py $device
    poetry update
    poetry build --format wheel
    mv ./pyproject.toml ./pyproject_${device}.toml
    mv ./poetry.lock ./poetry_${device}.lock
done
