[tool.poetry]
# filled in by set_package_version.py
name = "{package_name}"
version = "0.0.3"
description = "Medusa: 4D face reconstruction and analysis"
authors = ["Lukas Snoek <lukassnoek@gmail.com>"]
license = "BSD-3-Clause"
readme = "README.md"
homepage = "https://medusa.lukas-snoek.com/medusa"
repository = "https://github.com/medusa-4D/medusa"
documentation = "https://medusa.lukas-snoek.com/medusa"
keywords = ["face reconstruction", "face detection", "face movement"]
classifiers = [
    "Intended Audience :: Science/Research",
    "License :: Free for non-commercial use",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Artificial Intelligence"
]
# Needed when building medusa-gpu version
packages = [{include = "medusa"}]

[tool.poetry.dependencies]
python = "3.9.*"
click = ">=8.1.3"
torch = [
    { markers = "sys_platform == 'linux'", url = "https://download.pytorch.org/whl/{device}/torch-1.13.1%2B{device}-cp39-cp39-linux_x86_64.whl" },
    { markers = "sys_platform == 'win32'", url = "https://download.pytorch.org/whl/{device}/torch-1.13.1%2B{device}-cp39-cp39-win_amd64.whl" }
]
torchvision = [
    { markers = "sys_platform == 'linux'", url = "https://download.pytorch.org/whl/{device}/torchvision-0.14.1%2B{device}-cp39-cp39-linux_x86_64.whl" },
    { markers = "sys_platform == 'win32'", url = "https://download.pytorch.org/whl/{device}/torchvision-0.14.1%2B{device}-cp39-cp39-win_amd64.whl" }
]
# pytorch3d wheels only available for cuda, so will be removed when building cpu package
pytorch3d = [
    { markers = "sys_platform == 'linux'", url = "https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py39_{device}_pyt1131/pytorch3d-0.7.2-cp39-cp39-linux_x86_64.whl" }
]
pandas = ">=1.5.1"
numpy = ">=1.23.4"
tqdm = ">=4.64.1"
opencv-python = ">=4.6.0.66"
PyYAML = ">=6.0"
h5py = ">=3.7.0"
trimesh = ">=3.16.2"
pyrender = ">=0.1.45"
matplotlib = ">=3.6.2"
gdown = ">=4.5.3"
kornia = ">=0.6.8"
mediapipe = { version = ">=0.8.11", markers = "platform_system != 'Darwin' and platform_machine != 'arm64'" }
mediapipe-silicon = { version = ">=0.8.11", markers = "platform_system == 'Darwin' and platform_machine == 'arm64'" }
onnxruntime-gpu = ">=1.13.1"
chumpy = {git = "https://github.com/lukassnoek/chumpy.git"}
av = ">=10.0.0"

[tool.poetry.group.dev.dependencies]
jupyter-book = ">=0.13.1"
sphinx-autoapi = ">=2.0.0"
pytest = ">=7.2.0"
nbval = ">=0.9.6"
coverage = ">=6.5.0"
pre-commit = ">=2.20.0"
interrogate = ">=1.5.0"

[tool.poetry.scripts]
medusa_download_ext_data = "medusa.cli:download_ext_data"
medusa_videorecon = "medusa.cli:videorecon_cmd"
medusa_videorender = "medusa.cli:videorender_cmd"
medusa_regenerate_example_recon_data = "medusa.data.regenerate_example_recon_data:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
