[build-system]
requires = [ "poetry-core",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "medusa-gpu"
version = "0.0.3"
description = "Medusa: 4D face reconstruction and analysis"
authors = [ "Lukas Snoek <lukassnoek@gmail.com>",]
license = "BSD-3-Clause"
readme = "README.md"
homepage = "https://medusa.lukas-snoek.com/medusa"
repository = "https://github.com/medusa-4D/medusa"
documentation = "https://medusa.lukas-snoek.com/medusa"
keywords = [ "face reconstruction", "face detection", "face movement",]
classifiers = [ "Intended Audience :: Science/Research", "License :: Free for non-commercial use", "Programming Language :: Python :: 3", "Topic :: Scientific/Engineering :: Artificial Intelligence",]
[[tool.poetry.packages]]
include = "medusa"

[tool.poetry.dependencies]
python = "3.9.*"
click = ">=8.1.3"
pandas = ">=1.5.1"
numpy = ">=1.23.4"
tqdm = ">=4.64.1"
opencv-python = ">=4.6.0.66"
PyYAML = ">=6.0"
h5py = ">=3.7.0"
trimesh = ">=3.16.2"
pyrender = ">=0.1.45"
matplotlib = ">=3.6.2"
gdown = ">=4.5.3"
kornia = ">=0.6.8"
av = ">=10.0.0"
[[tool.poetry.dependencies.torch]]
markers = "sys_platform == 'linux'"
url = "https://download.pytorch.org/whl/cu116/torch-1.13.1%2Bcu116-cp39-cp39-linux_x86_64.whl"

[[tool.poetry.dependencies.torch]]
markers = "sys_platform == 'win32'"
url = "https://download.pytorch.org/whl/cu116/torch-1.13.1%2Bcu116-cp39-cp39-win_amd64.whl"

[[tool.poetry.dependencies.torchvision]]
markers = "sys_platform == 'linux'"
url = "https://download.pytorch.org/whl/cu116/torchvision-0.14.1%2Bcu116-cp39-cp39-linux_x86_64.whl"

[[tool.poetry.dependencies.torchvision]]
markers = "sys_platform == 'win32'"
url = "https://download.pytorch.org/whl/cu116/torchvision-0.14.1%2Bcu116-cp39-cp39-win_amd64.whl"

[[tool.poetry.dependencies.pytorch3d]]
markers = "sys_platform == 'linux'"
url = "https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py39_cu116_pyt1131/pytorch3d-0.7.2-cp39-cp39-linux_x86_64.whl"

[tool.poetry.scripts]
medusa_download_ext_data = "medusa.cli:download_ext_data"
medusa_videorecon = "medusa.cli:videorecon_cmd"
medusa_videorender = "medusa.cli:videorender_cmd"
medusa_regenerate_example_recon_data = "medusa.data.regenerate_example_recon_data:main"

[tool.poetry.dependencies.mediapipe]
version = ">=0.8.11"
markers = "platform_system != 'Darwin' and platform_machine != 'arm64'"

[tool.poetry.dependencies.mediapipe-silicon]
version = ">=0.8.11"
markers = "platform_system == 'Darwin' and platform_machine == 'arm64'"

[tool.poetry.dependencies.onnxruntime-gpu]
version = ">=1.13.1"
markers = "platform_system != 'Darwin' and platform_machine != 'arm64'"

[tool.poetry.dependencies.onnxruntime-silicon]
version = ">=1.13.1"
markers = "platform_system == 'Darwin' and platform_machine == 'arm64'"

[tool.poetry.dependencies.chumpy]
git = "https://github.com/lukassnoek/chumpy.git"

[tool.poetry.group.dev.dependencies]
jupyter-book = ">=0.13.1"
sphinx-autoapi = ">=2.0.0"
pytest = ">=7.2.0"
nbval = ">=0.9.6"
coverage = ">=6.5.0"
pre-commit = ">=2.20.0"
interrogate = ">=1.5.0"
