FAN:
    device: cuda
    lm_type: 2D
    face_detector: sfd

DECA:
    model_path: data/deca_model.tar
    emoca_path: data/emoca.ckpt
    use_emoca: True
    topology_path: data/head_template.obj
    use_tex: True
    uv_size: 256
    image_size: 224
    face_eye_mask_path: data/uv_face_eye_mask.png
    face_mask_path: data/uv_face_mask.png
    fixed_displacement_path: data/fixed_displacement_256.npy
    mean_tex_path: data/mean_texture.jpg

E_flame:
    n_shape: 100
    n_exp: 50
    n_tex: 50
    n_cam: 3
    n_pose: 6
    n_light: 27

E_detail:
    n_detail: 128

D_flame:
    flame_model_path: data/generic_model.pkl
    flame_lmk_embedding_path: data/landmark_embedding.npy
    tex_type: BFM
    tex_path: data/FLAME_albedo_from_BFM.npz

D_detail:
    max_z: 0.01