name: setup-medusa
description: "Sets up environment for Medusa"
inputs:
  python-version:
    description: "Python version to install"
    default: "3.10"

runs:
  using: "composite"
  steps:
  - name: Install GLU
    shell: bash
    run: sudo apt install -y freeglut3-dev
  - name: Get Medusa repository
    uses: actions/checkout@v3
  - name: Install Poetry Action
    uses: snok/install-poetry@v1.3.3
  - name: Set up Python ${{ inputs.python-version }}
    uses: actions/setup-python@v4
    with:
      python-version: ${{ inputs.python-version }}
      cache: 'poetry'
  - name: Install Medusa
    shell: bash
    run: poetry install
