name: setup-medusa
description: "Sets up environment for Medusa"
inputs:
  python-version:
    description: "Python version to install"
    default: 3.9

runs:
  using: "composite"
  steps:
  # Getting everything ready
  - uses: actions/checkout@v3
  - name: Install Poetry Action
    uses: snok/install-poetry@v1.3.3
  - name: Set up Python ${{ inputs.python-version }}
    uses: actions/setup-python@v4
    with:
      python-version: ${{ inputs.python-version }}
      cache: 'poetry'
  - name: Install GLU
    shell: bash
    run: sudo apt install -y freeglut3-dev
  # Install package + deps + download data
  - name: Install Medusa
    shell: bash
    run: |
      python ./set_package_version.py cpu
      poetry install
