#!/usr/bin/env bash
rm -f tests/test_viz/*/*.mp4 tests/test_viz/*/*.png tests/test_viz/*/*.tsv tests/test_viz/*/*.png tests/test_viz/*/*.obj
coverage run --source=medusa/ -m pytest --disable-warnings tests/
