name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install GLU
      run: sudo apt install -y freeglut-devel
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install .
    - name: Test with pytest
      run: |
        ./run_tests
