name: docs

on:
  push:
    branches:
      - master

jobs:
  build-docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      # Generate + deploy documentation
      - uses: actions/checkout@v3
      - name: Setup Medusa
        uses: ./.github/actions/setup-medusa
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build docs
        shell: bash
        run: poetry run ./docs/build_docs
      - name: Publish docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
