name: Setup Medusa

on:
  push:
    branches:
      - master
  workflow_call:

jobs:

  setup:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9]

    steps:
    # Getting everything ready
    - uses: actions/checkout@v3
    - name: Install Poetry Action
      uses: snok/install-poetry@v1.3.3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'poetry'
    - name: Install GLU
      run: sudo apt install -y freeglut3-dev

    # Install package + deps + download data
    - name: Install Medusa
      run: poetry install
